name: parastell_env
channels:
  - conda-forge
dependencies:
  - cadquery
  - moab >=5.5.1[build=nompi_tempest_*]
  - cad_to_dagmc >=0.9.1
  - openmc >=0.15.0[build=dagmc_nompi_*]
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
      - netcdf4
      - pyyaml
      - pytest
      - git+https://github.com/svalinn/pydagmc.git
